### ISSUE TITLE
Dashboard webpage doesnt work in offline environment

### ISSUE THREAD

**Issue by justinrush** [reactiveops/polaris#102]
The Dashboard web page will not work in an offline environment because it tries to pull in javascript and css files from the internet.  By default we prevent accessing the internet and are generally opposed to allowing accessing.  These javascript and CSS files should be included in the docker image.

**Comment by robscott** [comment]
Hey @justinrush, this is a good idea that we hadn't previously considered, we've fixed it in 0.1.2.

**Comment by makeacode** [comment]
I just upgraded to version 3.0.0 using the helm chart and this seems to have regressed.  the webpage will load eventually but the bootstrap.min.js fails and page doesn't render properly
