### ISSUE TITLE
Only two namespaces inspected

### ISSUE THREAD

**Issue by marcecaro** [reactiveops/polaris#106]
I am trying Polaris in a cluster with 11 namespaces, but only kube-syste, and polaris are shown in the report.

Any clue?

Thanks

**Comment by robscott** [comment]
Hey @marcecaro, thanks for checking in. Right now Polaris only validates deployments, so if your other namespaces don't have deployment resources, they won't show up. If they do have deployments, is Polaris logging anything useful?

**Comment by marcecaro** [comment]
Yes it is really useful for big solutions and it would help to keep metrics. 
We have several teams that are still using replica controllers.  And some of them Daemons and ReplicaSets. 
Are you going to cover those resources in the future?

Thanks

**Comment by robscott** [comment]
Yep, it's on our [roadmap](https://github.com/reactiveops/polaris/blob/master/ROADMAP.md#new-controller-types), we hope to get those kinds of resources included shortly. I've created an issue that can track progress on that feature here: https://github.com/reactiveops/polaris/issues/107. Thanks for letting us know it would be useful!

**Comment by marcecaro** [comment]
Thank you very much, and really nice work!
