### ISSUE TITLE
how often does data refresh? 

### ISSUE THREAD

**Issue by stevesea** [reactiveops/polaris#109]
launched Polaris in my cluster, found some problems with my deployments.  Fixed a few things, re-deployed the offending applications... No change to the dashboard (even after an hour or two).

If I delete the Polaris pod, it'll restart and shows the expected changed errors/warnings. 

How often does polaris scan the cluster? How do I trigger a new scan?

**Comment by robscott** [comment]
Hey @stevesea, thanks for catching that! It is supposed to refresh on each dashboard page load, but it looks like one of our recent additions (support for parsing yaml files) ended up changing the behavior there. We'll work on a fix.

**Comment by robscott** [comment]
Hey @stevesea, this should be fixed with our latest 0.1.3 release, thanks for filing the issue!

**Comment by stevesea** [comment]
Thank you for open-sourcing this tool! So far, my team really loves it!
