### ISSUE TITLE
Readiness probes should be ignored on initContainers

### ISSUE THREAD

**Issue by irasnyd** [reactiveops/polaris#112]
The Kubernetes documentation states that readiness probes are not supported on initContainers:

https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

> Also, Init Containers do not support readiness probes because they must run to completion before the Pod can be ready.

Based on this, I think that lack of a readiness probe should be ignored for initContainers. This would bring my cluster's score up a bit. :smiley:

**Comment by robscott** [comment]
Great catch, thanks! We'll work on fixing that.
