### ISSUE TITLE
Expose cluster name?

### ISSUE THREAD

**Issue by alexcurtin** [reactiveops/polaris#124]
If you run polaris in many clusters, without creating an ingress (custom dns per each cluster), it would be nice if the header area also showed the cluster name (can be read from kubeconfig?) 

Thoughts?

**Comment by bobby-brennan** [comment]
There are a few ways a "cluster name" might be specified, so we'll probably use some combination of:
* A command-line arg that specifies cluster name
* The `name` field in ~/.kube/config`
* (maybe) annotations on Node objects

Thanks for the feature request!

**Comment by bobby-brennan** [comment]
As of `0.2.0`, we've added a `--display-name` flag, and will display the hostname of the cluster if it's not specified.

Hope that helps!
