### ISSUE TITLE
Resources: limits/requests should be ignored for initContainers

### ISSUE THREAD

**Issue by alexcurtin** [reactiveops/polaris#125]
Currently, `polaris` reports a warning of cpu/memory limits and requests missing on initContainers but per https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources I don't think that setting limits/requests on initContainers is standard / best practice?

Correct me if wrong!

**Comment by robscott** [comment]
Hey @alexcurtin, this is a great find, thanks! Although these can be useful in some cases, I think those are quite rare, so we're disabling these checks for init containers by default. I've opened a PR for that referenced above, we should get this out in our next release.

**Comment by bobby-brennan** [comment]
Fixed in `0.1.5`. Thanks for the report!
