### ISSUE TITLE
Remove Gopkg.lock and vendor folder

### ISSUE THREAD

**Issue by kacejot** [reactiveops/polaris#137]
This ones are not necessary to store in the repo. It makes repo larger and longer to download.
Contributor can restore dependencies with dep util instead.

**Comment by bobby-brennan** [comment]
We've discussed this a bunch internally. The issue with removing `./vendor` is that it makes it hard to reproduce builds, thanks to the decentralized nature of git. For example, someone could delete the repository for one of our dependencies.

Open to suggestions for getting around this, but reproducible builds are a priority for us.

**Comment by kacejot** [comment]
Agreed.
