### ISSUE TITLE
CI/CD uses branch of reactiveops/charts rather than master

### ISSUE THREAD

**Issue by bobby-brennan** [reactiveops/polaris#154]
If a fix is merged into the `master` branch, but not the `polaris-latest` branch, it won't make it into polaris releases.

**Comment by endzyme** [comment]
Would it be more prudent to tag a commit as Polaris-latest instead of actively sync a branch?

**Comment by endzyme** [comment]
Actually, by having a branch that isn't `master`, isn't that indicating that master may not be releasable? Let's connect on this on Monday, I'm interested to understand the pros and cons of these methods and how automated each one can be for releases. :D

**Comment by endzyme** [comment]
I think this is resolved with #156

**Comment by endzyme** [comment]
TL;DR - the process for managing both helm chart and local repo deploy.yml changes is outlined in CONTRIBUTING.md.
